# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadfile/loadfilepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadFileDialog(object):
    def setupUi(self, LoadFileDialog):
        LoadFileDialog.setObjectName("LoadFileDialog")
        LoadFileDialog.resize(900, 640)
        LoadFileDialog.setMinimumSize(QtCore.QSize(900, 640))
        LoadFileDialog.setMaximumSize(QtCore.QSize(900, 640))
        LoadFileDialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoadFileDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(LoadFileDialog)
        self.stackedWidget.setMinimumSize(QtCore.QSize(880, 620))
        self.stackedWidget.setMaximumSize(QtCore.QSize(880, 620))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("color: #0A2A49;")
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_cur_razdel = QtWidgets.QLabel(self.page)
        self.load_cur_razdel.setMinimumSize(QtCore.QSize(750, 25))
        self.load_cur_razdel.setMaximumSize(QtCore.QSize(750, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load_cur_razdel.setFont(font)
        self.load_cur_razdel.setText("")
        self.load_cur_razdel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.load_cur_razdel.setObjectName("load_cur_razdel")
        self.verticalLayout_2.addWidget(self.load_cur_razdel)
        self.load_cur_vopros = QtWidgets.QLabel(self.page)
        self.load_cur_vopros.setMinimumSize(QtCore.QSize(750, 25))
        self.load_cur_vopros.setMaximumSize(QtCore.QSize(750, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load_cur_vopros.setFont(font)
        self.load_cur_vopros.setText("")
        self.load_cur_vopros.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.load_cur_vopros.setObjectName("load_cur_vopros")
        self.verticalLayout_2.addWidget(self.load_cur_vopros)
        self.load_cur_otvet = QtWidgets.QLabel(self.page)
        self.load_cur_otvet.setMinimumSize(QtCore.QSize(750, 25))
        self.load_cur_otvet.setMaximumSize(QtCore.QSize(750, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load_cur_otvet.setFont(font)
        self.load_cur_otvet.setText("")
        self.load_cur_otvet.setObjectName("load_cur_otvet")
        self.verticalLayout_2.addWidget(self.load_cur_otvet)
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setMinimumSize(QtCore.QSize(750, 25))
        self.progressBar.setMaximumSize(QtCore.QSize(750, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.chooseFileBtn = QtWidgets.QPushButton(self.page)
        self.chooseFileBtn.setMinimumSize(QtCore.QSize(400, 60))
        self.chooseFileBtn.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.chooseFileBtn.setFont(font)
        self.chooseFileBtn.setStyleSheet("QPushButton {\n"
"    background-color: #0A2A49;\n"
"    border-radius: 25px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: #0B263B;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #0A2A49;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #1F4971;\n"
"    color: grey;\n"
"}")
        self.chooseFileBtn.setObjectName("chooseFileBtn")
        self.horizontalLayout_2.addWidget(self.chooseFileBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setSpacing(50)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setMinimumSize(QtCore.QSize(500, 40))
        self.label_2.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #0A2A49;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.closeDlgBtn = QtWidgets.QPushButton(self.page_2)
        self.closeDlgBtn.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.closeDlgBtn.setFont(font)
        self.closeDlgBtn.setStyleSheet("QPushButton {\n"
"    background-color: #0A2A49;\n"
"    border-radius: 25px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: #0E3459;\n"
" }\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: #0A2A49;\n"
" }\n"
"\n"
"QPushButton:disabled {\n"
"     background-color: #1F4971;\n"
"    color: grey;\n"
" }")
        self.closeDlgBtn.setObjectName("closeDlgBtn")
        self.horizontalLayout_5.addWidget(self.closeDlgBtn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(LoadFileDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoadFileDialog)

    def retranslateUi(self, LoadFileDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadFileDialog.setWindowTitle(_translate("LoadFileDialog", "Диалог загрузки файла"))
        self.chooseFileBtn.setText(_translate("LoadFileDialog", "Выбрать файл"))
        self.label_2.setText(_translate("LoadFileDialog", "Тест успешно добавлен"))
        self.closeDlgBtn.setText(_translate("LoadFileDialog", "Закрыть"))
